export const TODAY_MESSAGES_REQUEST = 'TODAY_MESSAGES_REQUEST'
export const TODAY_MESSAGES_SUCCESS = 'TODAY_MESSAGES_SUCCESS'
export const TODAY_MESSAGES_FAIL = 'TODAY_MESSAGES_FAIL'
export const TODAY_MESSAGES_RESET = 'TODAY_MESSAGES_RESET'

export const YESTERDAY_MESSAGES_REQUEST = 'YESTERDAY_MESSAGES_REQUEST'
export const YESTERDAY_MESSAGES_SUCCESS = 'YESTERDAY_MESSAGES_SUCCESS'
export const YESTERDAY_MESSAGES_FAIL = 'YESTERDAY_MESSAGES_FAIL'
export const YESTERDAY_MESSAGES_RESET = 'YESTERDAY_MESSAGES_RESET'

export const MONTH_MESSAGES_REQUEST = 'MONTH_MESSAGES_REQUEST'
export const MONTH_MESSAGES_SUCCESS = 'MONTH_MESSAGES_SUCCESS'
export const MONTH_MESSAGES_FAIL = 'MONTH_MESSAGES_FAIL'
export const MONTH_MESSAGES_RESET = 'MONTH_MESSAGES_RESET'

export const ALL_MESSAGES_REQUEST = 'ALL_MESSAGES_REQUEST'
export const ALL_MESSAGES_SUCCESS = 'ALL_MESSAGES_SUCCESS'
export const ALL_MESSAGES_FAIL = 'ALL_MESSAGES_FAIL'
export const ALL_MESSAGES_RESET = 'ALL_MESSAGES_RESET'

export const POST_MESSAGE_REQUEST = 'POST_MESSAGE_REQUEST'
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS'
export const POST_MESSAGE_FAIL = 'POST_MESSAGE_FAIL'
export const POST_MESSAGE_RESET = 'POST_MESSAGE_RESET'